# Scaffolding Notebook: Loading and Handling Data Files in Python

This notebook provides a minimal (and definitely non-comprehensive) introduction to loading and handling plain-text data files using Python and `numpy`.

## Objectives
1. Learn how to load plain-text data into arrays using `numpy.loadtxt`.
2. Handle different file formats, including single-column, multi-column, and delimited data.


## Example 1: Loading a Single-Column Data File

A single-column data file contains one value per line. For example:
1.2 2.3 3.4 4.5 5.6


We will simulate this file by creating and saving it, then load it into a 1D NumPy array.


In [1]:
# Create and save a single-column data file
with open('single_column.txt', 'w') as f:
    f.write("1.2\n2.3\n3.4\n4.5\n5.6\n")

# Load the data from the file into a 1D NumPy array
import numpy as np
data = np.loadtxt('single_column.txt')
print("Loaded single-column data:")
print(data)


Loaded single-column data:
[1.2 2.3 3.4 4.5 5.6]


## Example 2: Loading a Multi-Column Data File

A multi-column data file stores rows and columns of numbers. For example:


In [2]:
# Create and save a multi-column data file
with open('multi_column.txt', 'w') as f:
    f.write("1.0 2.0 3.0\n4.0 5.0 6.0\n7.0 8.0 9.0\n")

# Load the data from the file into a 2D NumPy array
data = np.loadtxt('multi_column.txt')
print("Loaded multi-column data:")
print(data)


Loaded multi-column data:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## Example 3: Handling Delimited Data

Some files use delimiters like commas or tabs instead of spaces. For example: 1.0,2.0,3.0 4.0,5.0,6.0 7.0,8.0,9.0

We will simulate this file, save it, and load its content using the `delimiter` argument in `numpy.loadtxt`.


In [3]:
# Create and save a comma-separated data file
with open('comma_separated.txt', 'w') as f:
    f.write("1.0,2.0,3.0\n4.0,5.0,6.0\n7.0,8.0,9.0\n")

# Load the data from the file using a comma as the delimiter
data = np.loadtxt('comma_separated.txt', delimiter=',')
print("Loaded comma-separated data:")
print(data)


Loaded comma-separated data:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
